### ISSUE TITLE
Conflicting AWS and HF docs for AWS inf instances, confused about which one to follow

### ISSUE THREAD

**Issue by sidyakinian** [philschmid/huggingface-sagemaker-workshop-series#9]
I'm trying to set up inference on AWS inf for a pretrained HF transformer. I followed [this HF tutorial](https://huggingface.co/blog/bert-inferentia-sagemaker) and ran into errors, opened [an issue on aws-neuron-sdk repo](https://github.com/aws/aws-neuron-sdk/issues/462#issuecomment-1203355388), was told that env setup is wrong. I'm quite confused now whether I should follow [AWS tutorials](https://github.com/aws/aws-neuron-sdk/blob/master/src/examples/pytorch/bert_tutorial/tutorial_pretrained_bert.ipynb), which advise to setup env according to[ this AWS doc](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/pytorch-setup/pytorch-install.html), or [HF tutorials](https://huggingface.co/blog/bert-inferentia-sagemaker) which setup env with two pip install lines. Would appreciate the help!

**Comment by philschmid** [comment]
Hey @sidyakinian, 

The [tutorial](https://huggingface.co/blog/bert-inferentia-sagemaker) uses the exact same setup than the [AWS Doc](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/pytorch-setup/pytorch-install.html) see: https://awsdocs-neuron.readthedocs-hosted.com/en/latest/neuron-intro/pytorch-setup/pytorch-install.html#compile-on-compute-instance.

```bash
# Note: There is no DLAMI Conda environment for this framework version
#       Framework will be installed/updated inside a Python environment

# Activate PyTorch
source activate aws_neuron_pytorch_p36

# Set Pip repository  to point to the Neuron repository
pip config set global.extra-index-url https://pip.repos.neuron.amazonaws.com

#Install Neuron PyTorch
pip install torch-neuron==1.9.1.* neuron-cc[tensorflow] "protobuf<4" torchvision
```

**Comment by sidyakinian** [comment]
@philschmid Makes sense, sorry, got a little confused with torch versions. Thanks!
